### ISSUE TITLE
How to run the bot ? 

### ISSUE THREAD

**Issue by Matduke** [aj-4/tinder-swipe-bot#29]
Hi, 

Please, what is the next step after putting chromedriver in /usr/local/bin ? 

Thank you !

**Comment by Matduke** [comment]
I have this error after run the .py: 

Traceback (most recent call last):
  File "tinder_bot.py", line 1, in <module>
    from selenium import webdriver
ImportError: No module named selenium


>>> pip install selenium
  File "<stdin>", line 1
    pip install selenium
              ^
SyntaxError: invalid syntax
>>>
